services:
  # Base de Datos Relacional (Para Booking.API)
  ticketflow-db:
    image: postgres:16-alpine
    container_name: ticketflow-postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: YourSecurePassword123!
      POSTGRES_DB: TicketFlow_Booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketflow-network

  # Base de Datos NoSQL (Para Notification.Worker)
  ticketflow-nosql:
    image: mongo:latest
    container_name: ticketflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ticketflow-network
 
  notification-worker:
    image: ticketflow-notification-worker
    container_name: ticketflow-worker
    build:
      context: .  # Raíz de la solución para que Docker vea 'src' y 'shared'
      dockerfile: apps/Notification.Worker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      # CORREGIDO: Apunta al nombre del servicio 'ticketflow-nosql'
      - ConnectionStrings__MongoConnection=mongodb://ticketflow-nosql:27017/TicketFlowDb
      # 🚀 VARIABLES ENLAZADAS AL ARCHIVO .ENV:
      - AWS__Region=${AWS_REGION}
      - AWS__BucketName=${AWS_BUCKET_NAME}
      - AWS__AccessKeyId=${AWS_ACCESS_KEY_ID}
      - AWS__SecretAccessKey=${AWS_SECRET_ACCESS_KEY}
      # 🎛️ NUEVAS: VARIABLES DE ENTORNO PARA RABBITMQ (Mapeadas de appsettings)
      - RabbitMq__Host=ticketflow-bus  # ⚠️ Asegúrate de que coincida con el nombre de tu servicio de RabbitMQ
      - RabbitMq__Port=5672
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      # Variables para enviar correos electronicos
      - EmailConfig__Email=${EMAILCONFIG__EMAIL}
      - EmailConfig__PasswordApp=${EMAILCONFIG__PASSWORDAPP}
    depends_on:
      - ticketflow-nosql  # CORREGIDO: Nombre del servicio correspondiente
      - ticketflow-bus
    networks:
      - ticketflow-network

  # Bus de Eventos (Comunicación Asíncrona)
  ticketflow-bus:
    image: rabbitmq:3-management-alpine
    container_name: ticketflow-rabbitmq
    ports:
      - "5672:5672"   # Puerto de comunicación de datos
      - "15672:15672" # Panel de control visual de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ticketflow-network

  # API de Reservas (Booking.API)
  booking-api:
    build:
      context: .
      dockerfile: apps/Booking.API/Dockerfile
    container_name: ticketflow-booking-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - ticketflow-db
    networks:
      - ticketflow-network

volumes:
  postgres_data:
  mongo_data:
  
networks:
  ticketflow-network:
    driver: bridge